spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skillswap
    username: root
    password: Panda@1010$$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: yoursecretkey